services:
  backend:
    image: perfufu/projetdocker-backend:latest
    build:
      context: ../back
      dockerfile: ../docker/Dockerfile.backend
    container_name: back
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: docker
      DATABASE_USER: docker
    secrets:
      - db_password
    networks:
      - frontend_net
      - backend_net

  db:
    image: perfufu/projetdocker-db:latest
    build:
      context: ../database
      dockerfile: ../docker/Dockerfile.bdd
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "mysql", "-u", "docker", "-proot", "docker", "-e", "SELECT 1 FROM users LIMIT 1;"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    image: perfufu/projetdocker-frontend:latest
    build:
      context: ../front
      dockerfile: ../docker/Dockerfile.frontend
    container_name: front
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - frontend_net


networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  db_data: